Deployment 1

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,24 +22,24 @@ jobs:
           cd Application
           printf "%s" "${{ secrets.ENTIRE_ENV }}" > .env
 
-      - name: Docker Install
-        uses: docker-practice/actions-setup-docker@master
-        timeout-minutes: 12
+      # - name: Docker Install
+      #   uses: docker-practice/actions-setup-docker@master
+      #   timeout-minutes: 12
         
-      - name: Docker System Cleanup (Prevent Disk Space Errors)
-        run: |
-          docker system prune -af --volumes
-          docker builder prune --all --force
+      # - name: Docker System Cleanup (Prevent Disk Space Errors)
+      #   run: |
+      #     docker system prune -af --volumes
+      #     docker builder prune --all --force
 
 
-      - name: Docker Compose Build
-        run: |
-          cd Application
-          set -x
+      # - name: Docker Compose Build
+      #   run: |
+      #     cd Application
+      #     set -x
 
-          docker version
+      #     docker version
 
-          docker compose build
+      #     docker compose build
 
 
       - name: Configure AWS CLI 
@@ -52,15 +52,15 @@ jobs:
         run: |
           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
 
-      - name: Tag and Push Docker Images to ECR  
-        run: |         
-          # Tag and push Streamlit app
-          docker tag streamlit-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:streamlit-app-latest
-          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:streamlit-app-latest
+      # - name: Tag and Push Docker Images to ECR  
+      #   run: |         
+      #     # Tag and push Streamlit app
+      #     docker tag streamlit-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:streamlit-app-latest
+      #     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:streamlit-app-latest
 
-          # Tag and push FastAPI app
-          docker tag fastapi-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:fastapi-app-latest
-          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:fastapi-app-latest
+      #     # Tag and push FastAPI app
+      #     docker tag fastapi-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:fastapi-app-latest
+      #     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:fastapi-app-latest
 
       - name: Create SSH Key File
         run: |
@@ -89,22 +89,18 @@ jobs:
           fi
 
           aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
+          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:streamlit-app-latest
+          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:fastapi-app-latest
 
-          STREAMLIT_IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${MY_REPO}:streamlit-app-latest
-          FASTAPI_IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${MY_REPO}:fastapi-app-latest
 
-          STREAMLIT_PORT=8501
-          FASTAPI_PORT=8000
+          docker stop $(docker ps -q --filter ancestor=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:streamlit-app-latest) || true
+          docker stop $(docker ps -q --filter ancestor=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:fastapi-app-latest) || true
+          docker rm $(docker ps -a -q --filter ancestor=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:streamlit-app-latest) || true
+          docker rm $(docker ps -a -q --filter ancestor=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:fastapi-app-latest) || true
+          
 
-          docker pull \$STREAMLIT_IMAGE
-          docker pull \$FASTAPI_IMAGE
-
-          docker ps -q --filter "ancestor=\$STREAMLIT_IMAGE" | xargs -r docker stop
-          docker ps -q --filter "ancestor=\$FASTAPI_IMAGE" | xargs -r docker stop
-
-          docker ps -a -q --filter "ancestor=\$STREAMLIT_IMAGE" | xargs -r docker rm
-          docker ps -a -q --filter "ancestor=\$FASTAPI_IMAGE" | xargs -r docker rm
-
-          docker run -d --env-file /home/ec2-user/.env -p \$STREAMLIT_PORT:8501 \$STREAMLIT_IMAGE
-          docker run -d --env-file /home/ec2-user/.env -p \$FASTAPI_PORT:8000 \$FASTAPI_IMAGE
+          docker run -d -p 8501:8501 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:streamlit-app-latest
+          docker run -d -p 8000:8000 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.MY_REPO }}:fastapi-app-latest
           EOF
+          
+        
